const REQUEST_INSERT_BOUNTY = 'REQUEST_INSERT_BOUNTY';
const RECEIVE_INSERT_BOUNTY_SUCCESS = 'RECEIVE_INSERT_BOUNTY_SUCCESS';
const RECEIVE_INSERT_BOUNTY_FAILURE = 'RECEIVE_INSERT_BOUNTY_FAILURE';

export {
  REQUEST_INSERT_BOUNTY,
  RECEIVE_INSERT_BOUNTY_SUCCESS,
  RECEIVE_INSERT_BOUNTY_FAILURE
};
