// action types
const REQUEST_INSERT_BOUNTY = 'REQUEST_INSERT_BOUNTY';
const RECEIVE_INSERT_BOUNTY_SUCCESS = 'RECEIVE_INSERT_BOUNTY_SUCCESS';
const RECEIVE_INSERT_BOUNTY_FAILURE = 'RECEIVE_INSERT_BOUNTY_FAILURE';
const PROCEED_TO_CHECKOUT = 'DONATION_CHECKOUT';

// state types
const DONATION_PROCESSING = 'DONATION_PROCESSING';
const DONATION_PROCESSED = 'DONATION_PROCESSED';
const DONATION_ERROR = 'DONATION_ERROR';

export {
  PROCEED_TO_CHECKOUT,
  REQUEST_INSERT_BOUNTY,
  RECEIVE_INSERT_BOUNTY_SUCCESS,
  RECEIVE_INSERT_BOUNTY_FAILURE,
  DONATION_PROCESSING,
  DONATION_PROCESSED,
  DONATION_ERROR
};
