const REQUEST_PUBLIC_USER = 'REQUEST_PUBLIC_USER';
const RECEIVE_PUBLIC_USER_SUCCESS = 'RECEIEVE_PUBLIC_USER';
const RECEIVE_PUBLIC_USER_FAILURE = 'RECEIVE_PUBLIC_USER_FAILURE';
const REQUEST_PUBLIC_BOUNTIES = 'REQUEST_PUBLIC_BOUNTIES';
const RECEIVE_PUBLIC_BOUNITES_SUCCESS = 'RECEIVE_PUBLIC_BOUNTIES_SUCCESS';
const RECEIVE_PUBLIC_BOUNTIES_FAILURE = 'RECEIVE_PUBLIC_BOUNTIES_FAILURE';

export {
  REQUEST_PUBLIC_USER,
  RECEIVE_PUBLIC_USER_SUCCESS,
  RECEIVE_PUBLIC_USER_FAILURE,
  REQUEST_PUBLIC_BOUNTIES,
  RECEIVE_PUBLIC_BOUNITES_SUCCESS,
  RECEIVE_PUBLIC_BOUNTIES_FAILURE
};
