const REQUEST_PUBLIC_USER = 'REQUEST_PUBLIC_USER';
const RECEIVE_PUBLIC_USER_SUCCESS = 'RECEIEVE_PUBLIC_USER';
const RECEIVE_PUBLIC_USER_FAILURE = 'RECEIVE_PUBLIC_USER_FAILURE';

export {
  REQUEST_PUBLIC_USER,
  RECEIVE_PUBLIC_USER_SUCCESS,
  RECEIVE_PUBLIC_USER_FAILURE
};
