const REQUEST_UPDATE_PAYPAL_EMAIL = 'REQUEST_UPDATE_PAYPAL_EMAIL';
const RECEIVE_UPDATE_PAYPAL_EMAIL_SUCCESS = 'RECEIVE_UPDATE_PAYPAL_EMAIL_SUCCESS';
const RECEIVE_UPDATE_PAYPAL_EMAIL_FAILURE = 'RECEIVE_UPDATE_PAYPAL_EMAIL_FAILURE';
const REQUEST_SETTINGS = 'REQUEST_SETTINGS';
const RECEIVE_SETTINGS_SUCCESS = 'RECEIEVE_SETTINGS_SUCCESS';
const RECEIVE_SETTINGS_FAILURE = 'RECEIVE_SETTINGS_FAILURE';

export {
  REQUEST_UPDATE_PAYPAL_EMAIL,
  RECEIVE_UPDATE_PAYPAL_EMAIL_SUCCESS,
  RECEIVE_UPDATE_PAYPAL_EMAIL_FAILURE,
  REQUEST_SETTINGS,
  RECEIVE_SETTINGS_SUCCESS,
  RECEIVE_SETTINGS_FAILURE
};
