const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
const RECEIVE_USER_INFO_SUCCESS = 'RECEIVE_USER_INFO_SUCCESS';
const RECEIVE_USER_INFO_FAILURE = 'RECEIVE_USER_INFO_FAILURE';
const REQUEST_TEST_ALERT = 'REQUEST_TEST_ALERT';
const RECEIVE_TEST_ALERT = 'RECEIVE_TEST_ALERT';

export {
  REQUEST_USER_INFO,
  RECEIVE_USER_INFO_SUCCESS,
  RECEIVE_USER_INFO_FAILURE,
  REQUEST_TEST_ALERT,
  RECEIVE_TEST_ALERT
};
