const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
const RECEIVE_USER_INFO_SUCCESS = 'RECEIVE_USER_INFO_SUCCESS';
const RECEIVE_USER_INFO_FAILURE = 'RECEIVE_USER_INFO_FAILURE';
const REQUEST_TEST_ALERT = 'REQUEST_TEST_ALERT';
const RECEIVE_TEST_ALERT = 'RECEIVE_TEST_ALERT';
const REQUEST_MY_DONATIONS = 'REQUEST_MY_DONATIONS';
const RECEIVE_MY_DONATIONS = 'RECEIVE_MY_DONATIONS';
const REQUEST_MY_BOUNTIES = 'REQUEST_MY_BOUNTIES';
const RECEIVE_MY_BOUNTIES = 'RECEIVE_MY_BOUNTIES';
const REQUEST_ACTIVATE_BOUNTY = 'REQUEST_ACCEPT_BOUNTY';
const RECEIVE_ACTIVATE_BOUNTY_SUCCESS = 'RECEIVE_ACTIVATE_BOUNTY_SUCCESS';
const RECEIVE_ACTIVATE_BOUNTY_FAILURE = 'RECEIVE_ACTIVATE_BOUNTY_FAILURE';
const REQUEST_REMOVE_BOUNTY = 'REQUEST_REMOVE_BOUNTY';
const RECEIVE_REMOVE_BOUNTY_SUCCESS = 'RECEIVE_REMOVE_BOUNTY_SUCCESS';
const RECEIVE_REMOVE_BOUNTY_FAILURE = 'RECEIVE_REMOVE_BOUNTY_FAILURE';
const REQUEST_VOTE_BOUNTY = 'REQUEST_VOTE_BOUNTY';
const RECEIVE_VOTE_BOUNTY = 'RECEIVE_VOTE_BOUNTY';
const REQUEST_ACTIVE_BOUNTY = 'REQUEST_ACTIVE_BOUNTY';
const RECEIVE_ACTIVE_BOUNTY = 'RECEIVE_ACTIVE_BOUNTY';
const REQUEST_DEACTIVATE_BOUNTY = 'REQUEST_DEACTIVATE_BOUNTY';
const RECEIVE_DEACTIVATE_BOUNTY = 'RECEIVE_DEACTIVATE_BOUNTY';

export {
  REQUEST_USER_INFO,
  RECEIVE_USER_INFO_SUCCESS,
  RECEIVE_USER_INFO_FAILURE,
  REQUEST_TEST_ALERT,
  RECEIVE_TEST_ALERT,
  REQUEST_MY_DONATIONS,
  RECEIVE_MY_DONATIONS,
  REQUEST_MY_BOUNTIES,
  RECEIVE_MY_BOUNTIES,
  REQUEST_ACTIVATE_BOUNTY,
  RECEIVE_ACTIVATE_BOUNTY_SUCCESS,
  RECEIVE_ACTIVATE_BOUNTY_FAILURE,
  REQUEST_REMOVE_BOUNTY,
  RECEIVE_REMOVE_BOUNTY_SUCCESS,
  RECEIVE_REMOVE_BOUNTY_FAILURE,
  REQUEST_VOTE_BOUNTY,
  RECEIVE_VOTE_BOUNTY,
  REQUEST_ACTIVE_BOUNTY,
  RECEIVE_ACTIVE_BOUNTY,
  REQUEST_DEACTIVATE_BOUNTY,
  RECEIVE_DEACTIVATE_BOUNTY
};
